<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{BiocCheck}
-->

# BiocCheck

`BiocCheck` is *opinionated software*, encapsulating what the Bioconductor 
core team feels are best practices for writing Bioconductor packages.
We've divided our opinions into three categories:

* **Required** (Equivalent to an ERROR in `R CMD check`). This means the package
  is missing something critical and it cannot be accepted into Bioconductor
  until the issue is fixed. (`BiocCheck` will continue past a `required`
  error, thus it is possible to have more than one, but it will end
  with an error code.)
* **Recommended** (Equivalent to a WARNING in `R CMD check`). We strongly
  encourage that these issues be fixed. In the weeks leading up to a
  Bioconductor release we will ask package authors to fix these issues.
* **Note**: Not necessarily something bad, just something we wanted to point out.

# Using `BiocCheck`

Most commonly you will use BiocCheck from your operating system command line,
as

    R CMD BiocCheck package

Where `package` is either a directory containing an R package, or a source
tarball (.tar.gz file). R CMD BiocCheck takes options which can be seen by running

    R CMD BiocCheck --help

```{r echo=FALSE}
suppressWarnings(
    output <- system2(file.path(Sys.getenv("R_HOME"), "bin", "R"),
        "CMD BiocCheck --help", stdout=TRUE, stderr=FALSE)
)
cat(paste(output, collapse="\n"))
```

# Installing BiocCheck




# Interpreting `BiocCheck` Messages

