library(testpkg0)
require(testpkg0)
library("testpkg0")
require("testpkg0")
library(package="testpkg0")
library(package=testpkg0)
require(package="testpkg0")
require(package=testpkg0)
require(package = teskpkg0)
require('testpkg0')
library('testpkg0')
