#!/usr/bin/env Rscript --vanilla

suppressPackageStartupMessages(library(methods))
suppressPackageStartupMessages(library(BiocCheck))


message("Hello from BiocCheck")

BiocCheck:::.BiocCheckFromCommandLine()

